name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - uses: actions/checkout@v2
    - name: Docker Compose Up 
      run: mkdir project && && mkdir mongo_dump && mkdir mysql_dump && docker-compose up -d && docker ps


